# Generated by Django 4.1.4 on 2023-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylist',
            old_name='status',
            new_name='completed',
        ),
    ]
